import { useEffect } from "react";

import Head from "next/head";
import Link from "next/link";

import Heading from "../../components/atoms/Headline/Headline";

import prismjs from "prismjs";

import "prismjs/themes/prism-coy.css";
require("prismjs/components/prism-scss");

import classes from "../../styles/layout.module.scss";

export default function CSS() {
  useEffect(() => {
    prismjs.highlightAll();
  }, []);

  return (
    <>
      <Head>
        <title>QA Best Practices</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section>
        <Heading section="1" id="javascript">
          QA (Quality Assurance)
        </Heading>
        <p>
          Entermedia uses{" "}
          <a
            href="https://entermedia-atx.atlassian.net/jira"
            target="_blank"
            rel="noreferrer"
          >
            Jira
          </a>{" "}
          to report and track project tasks, bugs, etc.
        </p>
        <Heading section="2" id="reporting-issues" showLink>
          Reporting Issues
        </Heading>
      </section>
    </>
  );
}
